name: Build Android Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android

      - name: Install Dependencies
        run: bun install

      - name: Prepare Signing Key
        run: |
          echo "${{ secrets.ANDROID_KEY_BASE64 }}" | base64 -d > src-tauri/gen/android/release.jks
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > src-tauri/gen/android/keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> src-tauri/gen/android/keystore.properties
          echo "storeFile=../release.jks" >> src-tauri/gen/android/keystore.properties

      - name: Build Android Release
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: bun tauri android build --apk true --split-per-abi

      - name: Prepare APKs for Release
        run: |
          mkdir -p ./final-artifacts
          find src-tauri/gen/android/app/build/outputs/apk/ -name "*.apk" -exec cp {} ./final-artifacts/ \;
          echo "Files in final-artifacts:"
          ls ./final-artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: final-artifacts/*.apk
          body: "Release of Lira Now"
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
